# Computación II: TP1: Redireccionamiento
# <federico.hernandez@um.edu.ar>
# <carlos.taffernaberry@um.edu.ar>

CC=gcc
CFLAGS=-g -Wall

tp1: tp1.c funciones.c
	$(CC) $(CFLAGS) -o $@ $^ 

clean:
	$(RM) tp1 *.o *~

