# Makefile tp1
CFLAGS=-Wall
pegar : main_pegar.c functions.c
	gcc -o pegar main_pegar.c functions.c

cortar : main_cortar.c functions.c
	gcc -o cortar main_cortar.c functions.c

clean:
	rm pegar cortar *.o
