CC=gcc
CFLAGS=-g -Wall
TARGETS=tp3

all: $(TARGETS)

tp3: main.c hijo.c parser.c
	$(CC) $(CFLAGS) -o $@ $^


test: tp3
	cat mensaje.txt | ./tp3 -p hola,mono,meme


clean:
	rm -f $(TARGETS) *~ core*


